services:
  postgres:
    image: postgres:16-alpine
    container_name: portfolio_db_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: portfolio_redis_local
    ports:
      - "6379:6379"
